development: 
  adapter: postgresql
  database: wikiful_development 
  encoding: unicode 
  user: wikiful 
  host: localhost 
  pool: 5 
  timeout: 5000


test: 
  adapter: postgresql 
  database: wikiful_test 
  encoding: unicode 
  user: wikiful 
  host: localhost 
  pool: 5 
  timeout: 5000

production: 
  adapter: postgresql 
  database: wikiful_production 
  encoding: unicode
  user: wikiful
  host: localhost
  pool: 5 
  timeout: 5000
