# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f065800a12c738f6735d6cef48bb6bca7dfce358a7ecf2dcb4505814760756f3b239970ecc54e145283e3b323dc9116d43fb3f913b6befecb3abd2bfebcf71b4

test:
  secret_key_base: b8ce2189bfa35f60846b8b1516219f6e5e69a0dcfc3fc950963ca1967356f5ae46fb7185dc17cc5c53f784fbe53820558375d95cac28a50bfb1ab255c8eab82e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
